config/routes.rb
Rails.application.routes.draw do

  get 'current_user' => 'application#current_user_json'

  post 'login_post' => 'public_pages#login_post'
  post 'teacher_google_sign_up' => 'public_pages#teacher_google_sign_up'
  post 'student_google_sign_up' => 'public_pages#student_google_sign_up'
  post 'google_login_post' => 'public_pages#google_login_post'
  post 'teacher_sign_up' => 'public_pages#teacher_sign_up'
  post 'student_sign_up' => 'public_pages#student_sign_up'
  
  get 'auth/:provider/callback', to: 'public_pages#google_auth_callback'
  get 'signout', to: 'public_pages#signout', as: 'signout'
  get 'signout_json' => 'public_pages#signout_json'
  get 'auth/failure', to: redirect('/')

  get 'privacy' => 'public_pages#privacy'
  get 'terms_of_service' => 'public_pages#terms_of_service'
  
  get 'teacher_home' => 'teacher_account#index'
  post 'teacher/update_classroom' => 'teacher_account#update_classroom'
  post 'teacher/save_new_classroom' => 'teacher_account#save_new_classroom'

  post 'teacher/delete_account' => 'teacher_account#delete_account'
  post 'teacher/save_settings' => 'teacher_account#save_settings'
  post 'teacher/update_password' => 'teacher_account#update_password'
  post 'teacher/convert_account' => 'teacher_account#convert_account'
  
  get 'classrooms_summary' => 'teacher_account#classrooms_summary'

  get 'teacher/classroom' => 'teacher_account#classroom'
  get 'teacher/classroom_tags' => 'teacher_account#classroom_tags'
  get 'teacher/classroom_activities_and_performances' => 'teacher_account#classroom_activities_and_performances'
  post 'teacher/save_student_performances' => 'teacher_account#save_student_performances'
  get 'teacher/student_performance' => 'teacher_account#student_performance'
  post 'teacher/save_verify' => 'teacher_account#save_verify'
  post 'teacher/save_activities_sort_order' => 'teacher_account#save_activities_sort_order'
  get 'teacher/export_data' => 'teacher_account#export_data'
  post 'teacher/save_reflection' => 'teacher_account#save_reflection'
  post 'teacher/save_student_performance' => 'teacher_account#save_student_performance'
  post 'teacher/save_all_student_performances' => 'teacher_account#save_all_student_performances'
  post 'teacher/save_student' => 'teacher_account#save_student'

  get 'teacher/activities_tags' => 'teacher_account#activities_tags'
  get 'teacher/teacher_activities_and_classroom_assignment' => 'teacher_account#teacher_activities_and_classroom_assignment'
  get 'teacher/teacher_activities_options' => 'teacher_account#teacher_activities_options'
  post 'teacher/save_teacher_activity_assignment_and_options' => 'teacher_account#save_teacher_activity_assignment_and_options'
  get 'teacher/teacher_activities_and_tags' => 'teacher_account#teacher_activities_and_tags'
  post 'teacher/save_new_activity' => 'teacher_account#save_new_activity'
  get 'teacher/activity' => 'teacher_account#activity'
  post 'teacher/update_activity/:id' => 'teacher_account#update_activity'
  get 'teacher/classroom_assignments' => 'teacher_account#classroom_assignments'
  post 'teacher/assign_activities' => 'teacher_account#assign_activities'
  get 'teacher/student_performance_count' => 'teacher_account#student_performance_count'
  post 'teacher/delete_activity' => 'teacher_account#delete_activity'
  post 'teacher/save_activity_assignments' => 'teacher_account#save_activity_assignments'

  get 'teacher/students' => 'teacher_account#students'
  get 'teacher/student' => 'teacher_account#student'
  get 'teacher/student_activities_and_performances' => 'teacher_account#student_activities_and_performances'
  get 'teacher/student_activity' => 'teacher_account#student_activity'
  get 'teacher/activity_and_performances' => 'teacher_account#activity_and_performances'
  get 'teacher/classroom_student_user' => 'teacher_account#classroom_student_user'
  post 'teacher/classroom_remove_student' => 'teacher_account#classroom_remove_student'
  post 'teacher/become_student' => 'teacher_account#become_student'

  get 'student_home' => 'student_account#index'
  get 'current_student_user' => 'student_account#current_student_user'

  get 'student/classrooms_summary' => 'student_account#classrooms_summary'
  get 'student/search_classroom_code' => 'student_account#search_classroom_code'
  get 'student/classroom_tags' => 'student_account#classroom_tags'
  post 'student/join_classroom' => 'student_account#join_classroom'

  get 'student/classroom' => 'student_account#classroom'
  get 'student/classroom_activities_and_performances' => 'student_account#classroom_activities_and_performances'
  get 'student/activity' => 'student_account#activity'
  post 'student/save_student_performance' => 'student_account#save_student_performance'
  post 'student/save_all_student_performances' => 'student_account#save_all_student_performances'
  get 'student/activity_and_performances' => 'student_account#activity_and_performances'
  post 'student/save_activity_goal' => 'student_account#save_activity_goal'

  post 'student/save_settings' => 'student_account#save_settings'
  post 'student/update_password' => 'student_account#update_password'
  post 'student/convert_account' => 'student_account#convert_account'

  get 'admin' => 'admin#home'
  get 'admin/logged_in' => 'admin#logged_in'
  post 'admin/google_login_post' => 'admin#google_login_post'
  post 'admin/search_users' => 'admin#search_users'
  get 'admin/sign_out' => 'admin#sign_out'
  post 'admin/become_user' => 'admin#become_user'
  get 'admin/summary_metrics' => 'admin#summary_metrics'
  get 'admin/user_metrics' => 'admin#user_metrics'
  post 'admin/update_password' => 'admin#update_password'
  post 'admin/upload_roster' => 'admin#upload_roster'

  root to: "public_pages#home"

  resources :sessions, only: [:create, :destroy]
  resources :classroom
  resources :activities
  resources :student_performances
  resources :activity_tags
  resources :teacher_users
  resources :student_users
  resources :student_performance_verifications

end

app/models/student_performance_verification.rb
class StudentPerformanceVerification < ActiveRecord::Base

	validates :classroom_activity_pairing_id, :student_user_id, presence: true
	validates_uniqueness_of :student_user_id, :scope => :classroom_activity_pairing_id

	belongs_to :classroom_activity_pairing
	belongs_to :student_user

end

app/helpers/student_performance_verifications_helper.rb
module StudentPerformanceVerificationsHelper
end

app/views/student_performance_verifications/_form.html.erb
<%= form_for(@student_performance_verification) do |f| %>
  <% if @student_performance_verification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_performance_verification.errors.count, "error") %> prohibited this student_performance_verification from being saved:</h2>

      <ul>
      <% @student_performance_verification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :classroom_activity_pairing_id %><br>
    <%= f.text_field :classroom_activity_pairing_id %>
  </div>
  <div class="field">
    <%= f.label :student_user_id %><br>
    <%= f.number_field :student_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_performance_verifications/edit.html.erb
<h1>Editing student_performance_verification</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_performance_verification %> |
<%= link_to 'Back', student_performance_verifications_path %>

app/views/student_performance_verifications/index.html.erb
<h1>Listing student_performance_verifications</h1>

<table>
  <thead>
    <tr>
      <th>Classroom activity pairing</th>
      <th>Student user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_performance_verifications.each do |student_performance_verification| %>
      <tr>
        <td><%= student_performance_verification.classroom_activity_pairing_id %></td>
        <td><%= student_performance_verification.student_user_id %></td>
        <td><%= link_to 'Show', student_performance_verification %></td>
        <td><%= link_to 'Edit', edit_student_performance_verification_path(student_performance_verification) %></td>
        <td><%= link_to 'Destroy', student_performance_verification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student performance verification', new_student_performance_verification_path %>

app/views/student_performance_verifications/new.html.erb
<h1>New student_performance_verification</h1>

<%= render 'form' %>

<%= link_to 'Back', student_performance_verifications_path %>

app/views/student_performance_verifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Classroom activity pairing:</strong>
  <%= @student_performance_verification.classroom_activity_pairing_id %>
</p>

<p>
  <strong>Student user:</strong>
  <%= @student_performance_verification.student_user_id %>
</p>

<%= link_to 'Edit', edit_student_performance_verification_path(@student_performance_verification) %> |
<%= link_to 'Back', student_performance_verifications_path %>